=== SpangleLabs/Hallo/store/convert.dtd
<!ELEMENT convert (prefix_group*,type*)>
<!ELEMENT prefix_group (name,prefix*)>
<!ELEMENT prefix (name,value)>
<!ELEMENT type (name,decimals?,base_unit,unit*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT decimals (#PCDATA)>
<!ELEMENT base_unit (unit)>
<!ELEMENT unit (name+,valid_prefix_group?,value,offset?,last_update?)>
<!ELEMENT valid_prefix_group (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT offset (#PCDATA)>
<!ELEMENT last_update (#PCDATA)>

=== SpangleLabs/Hallo/store/convert.xml
<?xml version="1.0" ?>
<!DOCTYPE convert
  SYSTEM 'convert.dtd'>
<convert>
	<prefix_group>
		<name>si</name>
		<prefix>
			<name>yotta</name>
			<abbr>Y</abbr>
			<value>1e+24</value>
		</prefix>
		<prefix>
			<name>zetta</name>
			<abbr>Z</abbr>
			<value>1e+21</value>
		</prefix>
		<prefix>
			<name>exa</name>
			<abbr>E</abbr>
			<value>1e+18</value>
		</prefix>
		<prefix>
			<name>peta</name>
			<abbr>P</abbr>
			<value>1000000000000000.0</value>
		</prefix>
		<prefix>
			<name>tera</name>
			<abbr>T</abbr>
			<value>1000000000000.0</value>
		</prefix>
		<prefix>
			<name>giga</name>
			<abbr>G</abbr>
			<value>1000000000.0</value>
		</prefix>
		<prefix>
			<name>mega</name>
			<abbr>M</abbr>
			<value>1000000.0</value>
		</prefix>
		<prefix>
			<name>kilo</name>
			<abbr>k</abbr>
			<value>1000.0</value>
		</prefix>
		<prefix>
			<name>hecto</name>
			<abbr>h</abbr>
			<value>100.0</value>
		</prefix>
		<prefix>
			<name>deca</name>
			<abbr>da</abbr>
			<value>10.0</value>
		</prefix>
		<prefix>
			<name>deci</name>
			<abbr>d</abbr>
			<value>0.1</value>
		</prefix>
		<prefix>
			<name>centi</name>
			<abbr>c</abbr>
			<value>0.01</value>
		</prefix>
		<prefix>
			<name>milli</name>
			<abbr>m</abbr>
			<value>0.001</value>
		</prefix>
		<prefix>
			<name>micro</name>
			<abbr>u</abbr>
			<value>1e-06</value>
		</prefix>
		<prefix>
			<name>nano</name>
			<abbr>n</abbr>
			<value>1e-09</value>
		</prefix>
		<prefix>
			<name>pico</name>
			<abbr>p</abbr>
			<value>1e-12</value>
		</prefix>
		<prefix>
			<name>femto</name>
			<abbr>f</abbr>
			<value>1e-15</value>
		</prefix>
		<prefix>
			<name>atto</name>
			<abbr>a</abbr>
			<value>1e-18</value>
		</prefix>
		<prefix>
			<name>zepto</name>
			<abbr>z</abbr>
			<value>1e-21</value>
		</prefix>
		<prefix>
			<name>yocto</name>
			<abbr>y</abbr>
			<value>1e-24</value>
		</prefix>
	</prefix_group>
	<prefix_group>
		<name>si-square</name>
		<prefix>
			<name>yotta</name>
			<abbr>Y</abbr>
			<value>1e+48</value>
		</prefix>
		<prefix>
			<name>zetta</name>
			<abbr>Z</abbr>
			<value>1e+42</value>
		</prefix>
		<prefix>
			<name>exa</name>
			<abbr>E</abbr>
			<value>1e+36</value>
		</prefix>
		<prefix>
			<name>peta</name>
			<abbr>P</abbr>
			<value>1e+30</value>
		</prefix>
		<prefix>
			<name>tera</name>
			<abbr>T</abbr>
			<value>1e+24</value>
		</prefix>
		<prefix>
			<name>giga</name>
			<abbr>G</abbr>
			<value>1e+18</value>
		</prefix>
		<prefix>
			<name>mega</name>
			<abbr>M</abbr>
			<value>1000000000000.0</value>
		</prefix>
		<prefix>
			<name>kilo</name>
			<abbr>k</abbr>
			<value>1000000.0</value>
		</prefix>
		<prefix>
			<name>hecto</name>
			<abbr>h</abbr>
			<value>10000.0</value>
		</prefix>
		<prefix>
			<name>deca</name>
			<abbr>da</abbr>
			<value>100.0</value>
		</prefix>
		<prefix>
			<name>deci</name>
			<abbr>d</abbr>
			<value>0.01</value>
		</prefix>
		<prefix>
			<name>centi</name>
			<abbr>c</abbr>
			<value>0.0001</value>
		</prefix>
		<prefix>
			<name>milli</name>
			<abbr>m</abbr>
			<value>1e-06</value>
		</prefix>
		<prefix>
			<name>micro</name>
			<abbr>u</abbr>
			<value>1e-12</value>
		</prefix>
		<prefix>
			<name>nano</name>
			<abbr>n</abbr>
			<value>1e-18</value>
		</prefix>
		<prefix>
			<name>pico</name>
			<abbr>p</abbr>
			<value>1e-24</value>
		</prefix>
		<prefix>
			<name>femto</name>
			<abbr>f</abbr>
			<value>1e-30</value>
		</prefix>
		<prefix>
			<name>atto</name>
			<abbr>a</abbr>
			<value>1e-36</value>
		</prefix>
		<prefix>
			<name>zepto</name>
			<abbr>z</abbr>
			<value>1e-42</value>
		</prefix>
		<prefix>
			<name>yocto</name>
			<abbr>y</abbr>
			<value>1e-48</value>
		</prefix>
	</prefix_group>
	<prefix_group>
		<name>si-cube</name>
		<prefix>
			<name>yotta</name>
			<abbr>Y</abbr>
			<value>1e+72</value>
		</prefix>
		<prefix>
			<name>zetta</name>
			<abbr>Z</abbr>
			<value>1e+63</value>
		</prefix>
		<prefix>
			<name>exa</name>
			<abbr>E</abbr>
			<value>1e+54</value>
		</prefix>
		<prefix>
			<name>peta</name>
			<abbr>P</abbr>
			<value>1e+45</value>
		</prefix>
		<prefix>
			<name>tera</name>
			<abbr>T</abbr>
			<value>1e+36</value>
		</prefix>
		<prefix>
			<name>giga</name>
			<abbr>G</abbr>
			<value>1e+27</value>
		</prefix>
		<prefix>
			<name>mega</name>
			<abbr>M</abbr>
			<value>1e+18</value>
		</prefix>
		<prefix>
			<name>kilo</name>
			<abbr>k</abbr>
			<value>1000000000.0</value>
		</prefix>
		<prefix>
			<name>hecto</name>
			<abbr>h</abbr>
			<value>1000000.0</value>
		</prefix>
		<prefix>
			<name>deca</name>
			<abbr>da</abbr>
			<value>1000.0</value>
		</prefix>
		<prefix>
			<name>deci</name>
			<abbr>d</abbr>
			<value>0.001</value>
		</prefix>
		<prefix>
			<name>centi</name>
			<abbr>c</abbr>
			<value>1e-06</value>
		</prefix>
		<prefix>
			<name>milli</name>
			<abbr>m</abbr>
			<value>1e-09</value>
		</prefix>
		<prefix>
			<name>micro</name>
			<abbr>u</abbr>
			<value>1e-18</value>
		</prefix>
		<prefix>
			<name>nano</name>
			<abbr>n</abbr>
			<value>1e-27</value>
		</prefix>
		<prefix>
			<name>pico</name>
			<abbr>p</abbr>
			<value>1e-36</value>
		</prefix>
		<prefix>
			<name>femto</name>
			<abbr>f</abbr>
			<value>1e-45</value>
		</prefix>
		<prefix>
			<name>atto</name>
			<abbr>a</abbr>
			<value>1e-54</value>
		</prefix>
		<prefix>
			<name>zepto</name>
			<abbr>z</abbr>
			<value>1e-63</value>
		</prefix>
		<prefix>
			<name>yocto</name>
			<abbr>y</abbr>
			<value>1e-72</value>
		</prefix>
	</prefix_group>
	<prefix_group>
		<name>si-big</name>
		<prefix>
			<name>yotta</name>
			<abbr>Y</abbr>
			<value>1e+24</value>
		</prefix>
		<prefix>
			<name>zetta</name>
			<abbr>Z</abbr>
			<value>1e+21</value>
		</prefix>
		<prefix>
			<name>exa</name>
			<abbr>E</abbr>
			<value>1e+18</value>
		</prefix>
		<prefix>
			<name>peta</name>
			<abbr>P</abbr>
			<value>1000000000000000.0</value>
		</prefix>
		<prefix>
			<name>tera</name>
			<abbr>T</abbr>
			<value>1000000000000.0</value>
		</prefix>
		<prefix>
			<name>giga</name>
			<abbr>G</abbr>
			<value>1000000000.0</value>
		</prefix>
		<prefix>
			<name>mega</name>
			<abbr>M</abbr>
			<value>1000000.0</value>
		</prefix>
		<prefix>
			<name>kilo</name>
			<abbr>k</abbr>
			<value>1000.0</value>
		</prefix>
		<prefix>
			<name>hecto</name>
			<abbr>h</abbr>
			<value>100.0</value>
		</prefix>
		<prefix>
			<name>deca</name>
			<abbr>da</abbr>
			<value>10.0</value>
		</prefix>
	</prefix_group>
	<prefix_group>
		<name>si-small</name>
		<prefix>
			<name>deci</name>
			<abbr>d</abbr>
			<value>0.1</value>
		</prefix>
		<prefix>
			<name>centi</name>
			<abbr>c</abbr>
			<value>0.01</value>
		</prefix>
		<prefix>
			<name>milli</name>
			<abbr>m</abbr>
			<value>0.001</value>
		</prefix>
		<prefix>
			<name>micro</name>
			<abbr>u</abbr>
			<value>1e-06</value>
		</prefix>
		<prefix>
			<name>nano</name>
			<abbr>n</abbr>
			<value>1e-09</value>
		</prefix>
		<prefix>
			<name>pico</name>
			<abbr>p</abbr>
			<value>1e-12</value>
		</prefix>
		<prefix>
			<name>femto</name>
			<abbr>f</abbr>
			<value>1e-15</value>
		</prefix>
		<prefix>
			<name>atto</name>
			<abbr>a</abbr>
			<value>1e-18</value>
		</prefix>
		<prefix>
			<name>zepto</name>
			<abbr>z</abbr>
			<value>1e-21</value>
		</prefix>
		<prefix>
			<name>yocto</name>
			<abbr>y</abbr>
			<value>1e-24</value>
		</prefix>
	</prefix_group>
	<prefix_group>
		<name>si-binary</name>
		<prefix>
			<name>yobi</name>
			<abbr>Yi</abbr>
			<value>1.2089258196146292e+24</value>
		</prefix>
		<prefix>
			<name>zebi</name>
			<abbr>Zi</abbr>
			<value>1.1805916207174113e+21</value>
		</prefix>
		<prefix>
			<name>exbi</name>
			<abbr>Ei</abbr>
			<value>1.152921504606847e+18</value>
		</prefix>
		<prefix>
			<name>pebi</name>
			<abbr>Pi</abbr>
			<value>1125899906842624.0</value>
		</prefix>
		<prefix>
			<name>tebi</name>
			<abbr>Ti</abbr>
			<value>1099511627776.0</value>
		</prefix>
		<prefix>
			<name>gibi</name>
			<abbr>Gi</abbr>
			<value>1073741824.0</value>
		</prefix>
		<prefix>
			<name>mebi</name>
			<abbr>Mi</abbr>
			<value>1048576.0</value>
		</prefix>
		<prefix>
			<name>kibi</name>
			<abbr>Ki</abbr>
			<value>1024.0</value>
		</prefix>
	</prefix_group>
	<type>
		<name>length</name>
		<decimals>3</decimals>
		<base_unit>
			<unit>
				<name>metres</name>
				<name>meters</name>
				<name>metre</name>
				<name>meter</name>
				<abbr>m</abbr>
				<valid_prefix_group>si</valid_prefix_group>
				<value>1.0</value>
			</unit>
		</base_unit>
		<unit>
			<name>light-years</name>
			<name>light-year</name>
			<name>lightyears</name>
			<name>lightyear</name>
			<abbr>ly</abbr>
			<value>9460730472580800.0</value>
		</unit>
		<unit>
			<name>miles</name>
			<name>mile</name>
			<value>1609.344</value>
		</unit>
		<unit>
			<name>inches</name>
			<name>inch</name>
			<abbr>in</abbr>
			<abbr>&quot;</abbr>
			<value>0.0254</value>
		</unit>
		<unit>
			<name>sticks</name>
			<name>stick</name>
			<value>0.508</value>
		</unit>
		<unit>
			<name>feet</name>
			<name>foot</name>
			<abbr>ft</abbr>
			<abbr>'</abbr>
			<value>0.3</value>
		</unit>
		<unit>
			<name>yards</name>
			<name>yard</name>
			<value>0.9</value>
		</unit>
		<unit>
			<name>marathons</name>
			<name>marathon</name>
			<value>42195.0</value>
		</unit>
		<unit>
			<name>cubits</name>
			<name>cubit</name>
			<value>0.4572</value>
		</unit>
		<unit>
			<name>astronomical units</name>
			<name>astronomical unit</name>
			<name>au</name>
			<value>149597870691.6</value>
		</unit>
		<unit>
			<name>parsecs</name>
			<name>parsec</name>
			<name>pc</name>
			<value>3.08567758e+16</value>
		</unit>
		<unit>
			<name>li</name>
			<value>500.0</value>
			<last_update>1403611590.123979</last_update>
		</unit>
		<unit>
			<name>chances</name>
			<name>chance</name>
			<name>chance flared xl</name>
			<name>xl flared chance</name>
			<name>xl chance flared</name>
			<valid_prefix_group>si</valid_prefix_group>
			<value>0.44196</value>
		</unit>
	</type>
	<type>
