=== SpangleLabs/Hallo/store/high_score_list.dtd
<!ELEMENT high_score_list (high_score*)>
<!ELEMENT high_score (game_name,player_name,score,date,data*)>
<!ELEMENT game_name (#PCDATA)>
<!ELEMENT player_name (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT data (var,value)>
<!ELEMENT var (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== SpangleLabs/Hallo/store/high_score_list.xml
<!DOCTYPE high_score_list SYSTEM "high_score_list.dtd"><high_score_list>
	<high_score>
		<game_name>higher_or_lower</game_name>
		<player_name>deer-spangle</player_name>
		<score>16 cards</score>
		<date>1388712085.5677264</date>
		<data>
			<var>cards</var>
			<value>16</value>
		</data>
	</high_score>
	<high_score>
		<game_name>ddr</game_name>
		<player_name>deer-spangle</player_name>
		<score>2 hits, 0.9512770175933838s lag</score>
		<date>1413126049.061674</date>
		<data>
			<var>hits</var>
			<value>2</value>
		</data>
		<data>
			<var>lag</var>
			<value>0.9512770175933838</value>
		</data>
	</high_score>
</high_score_list>
