=== SpangleLabs/Hallo/config/config.dtd
<!ELEMENT config (default_nick,default_prefix,default_full_name,function_dispatcher,server_list,user_group_list,permission_mask?)>
<!ELEMENT default_nick (#PCDATA)>
<!ELEMENT default_prefix (#PCDATA)>
<!ELEMENT default_full_name (#PCDATA)>
<!ELEMENT function_dispatcher (#PCDATA)>
<!ELEMENT server_list (server*)>


<!ELEMENT user_group_list (user_group*)>


<!ELEMENT permission_mask (right_list)>
<!ELEMENT right_list (right*)>
<!ELEMENT right (name,value)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>

=== SpangleLabs/Hallo/config/config-default.xml
<!DOCTYPE config SYSTEM "config.dtd"><config>
<default_nick>Hallo</default_nick>
<default_prefix>False</default_prefix>
<default_full_name>HalloBot HalloHost HalloServer :a bot by spangle</default_full_name>
<function_dispatcher>
	<module_list>
		<module>
			<name>AsciiArt</name>
		</module>
		<module>
			<name>Bio</name>
		</module>
		<module>
			<name>ChannelControl</name>
		</module>
		<module>
			<name>Convert</name>
		</module>
		<module>
			<name>Euler</name>
		</module>
		<module>
			<name>Furry</name>
		</module>
		<module>
			<name>Games</name>
		</module>
		<module>
			<name>HalloControl</name>
		</module>
		<module>
			<name>Lookup</name>
		</module>
		<module>
			<name>Math</name>
		</module>
		<module>
			<name>PermissionControl</name>
		</module>
		<module>
			<name>Pokemon</name>
		</module>
		<module>
			<name>Pony</name>
		</module>
		<module>
			<name>Random</name>
		</module>
		<module>
			<name>ServerControl</name>
		</module>
		<module>
			<name>Silly</name>
		</module>
		<module>
			<name>SillyEtd</name>
		</module>
	</module_list>
</function_dispatcher>
<server_list>
</server_list>
<user_group_list>
	<user_group>
		<name>god</name>
		<permission_mask>
			<right_list>
				<right>
					<name>function_JoinChannel</name>
					<value>True</value>
				</right>
				<right>
					<name>function_LeaveChannel</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Shutdown</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Disconnect</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Connect</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Say</name>
					<value>True</value>
				</right>
				<right>
					<name>function_EditServer</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ListUsers</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ListChannels</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Permissions</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ConfigSave</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ModuleReload</name>
					<value>True</value>
				</right>
				<right>
					<name>function_UpdateCurrencies</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ConvertSet</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ConvertAddType</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ConvertSetTypeDecimals</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ConvertRemoveUnit</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ConvertUnitAddName</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ConvertUnitAddAbbreviation</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ConvertUnitRemoveName</name>
					<value>True</value>
				</right>
				<right>
					<name>function_ConvertUnitSetPrefixGroup</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Longcat</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Deer</name>
					<value>True</value>
				</right>
				<right>
					<name>function_SilenceTheRabble</name>
					<value>True</value>
				</right>
				<right>
					<name>function_PokeTheAsshole</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Operator</name>
					<value>True</value>
				</right>
				<right>
					<name>function_DeOperator</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Voice</name>
					<value>True</value>
				</right>
				<right>
					<name>function_DeVoice</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Invite</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Mute</name>
					<value>True</value>
				</right>
				<right>
					<name>function_UnMute</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Kick</name>
					<value>True</value>
				</right>
			</right_list>
		</permission_mask>
	</user_group>
	<user_group>
		<name>operator</name>
		<permission_mask>
			<right_list>
				<right>
					<name>function_JoinChannel</name>
					<value>True</value>
				</right>
				<right>
					<name>function_LeaveChannel</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Say</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Deer</name>
					<value>True</value>
				</right>
				<right>
					<name>function_SilenceTheRabble</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Operator</name>
					<value>True</value>
				</right>
				<right>
					<name>function_DeOperator</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Voice</name>
					<value>True</value>
				</right>
				<right>
					<name>function_DeVoice</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Invite</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Mute</name>
					<value>True</value>
				</right>
				<right>
					<name>function_UnMute</name>
					<value>True</value>
				</right>
				<right>
					<name>function_Kick</name>
					<value>True</value>
				</right>
			</right_list>
		</permission_mask>
	</user_group>
</user_group_list>
<permission_mask>
	<right_list>
		<right>
			<name>invite_channel</name>
			<value>False</value>
		</right>
		<right>
			<name>default_function</name>
			<value>True</value>
		</right>
		<right>
			<name>function_JoinChannel</name>
			<value>False</value>
		</right>
		<right>
			<name>function_LeaveChannel</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Shutdown</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Disconnect</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Connect</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Say</name>
			<value>False</value>
		</right>
		<right>
			<name>function_EditServer</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ListUsers</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ListChannels</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Permissions</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ConfigSave</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ModuleReload</name>
			<value>False</value>
		</right>
		<right>
			<name>function_UpdateCurrencies</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ConvertSet</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ConvertAddType</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ConvertSetTypeDecimals</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ConvertRemoveUnit</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ConvertUnitAddName</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ConvertUnitAddAbbreviation</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ConvertUnitRemoveName</name>
			<value>False</value>
		</right>
		<right>
			<name>function_ConvertUnitSetPrefixGroup</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Longcat</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Deer</name>
			<value>False</value>
		</right>
		<right>
			<name>function_SilenceTheRabble</name>
			<value>False</value>
		</right>
		<right>
			<name>function_PokeTheAsshole</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Operator</name>
			<value>False</value>
		</right>
		<right>
			<name>function_DeOperator</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Voice</name>
			<value>False</value>
		</right>
		<right>
			<name>function_DeVoice</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Invite</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Mute</name>
			<value>False</value>
		</right>
		<right>
			<name>function_UnMute</name>
			<value>False</value>
		</right>
		<right>
			<name>function_Kick</name>
			<value>False</value>
		</right>
	</right_list>
</permission_mask>
<api_key_list>
</api_key_list>
</config>
